# Generated by Django 5.2.7 on 2026-02-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_author_delete_simpleuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
