# Generated by Django 5.2.7 on 2026-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='moderation_comment',
            field=models.TextField(blank=True, help_text='Причина отклонения (для администратора)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонён')], default='draft', max_length=10),
        ),
    ]
