# Generated by Django 5.2.7 on 2026-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_moderation_comment_recipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipes/img/%Y/%m/%d/'),
        ),
    ]
